name: Platform Deployment (Monitoring / Infra)

on:
  workflow_dispatch:
    inputs:
      component:
        description: "Platform component to deploy"
        required: true
        default: "monitoring"
        type: choice
        options:
          - monitoring

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: gkedemo-485903
  PROJECT_NUMBER: 531610217280
  REGION: us-central1
  CLUSTER_NAME: gke-demo
  CLUSTER_ZONE: us-central1-a

jobs:
  platform-deploy:
    name: Deploy platform component
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # -----------------------------
      # Authenticate using OIDC
      # -----------------------------
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions@gkedemo-485903.iam.gserviceaccount.com"

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      # -----------------------------
      # Get cluster credentials
      # -----------------------------
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --zone ${{ env.CLUSTER_ZONE }} \
            --project ${{ env.PROJECT_ID }}

      # -----------------------------
      # Deploy monitoring stack
      # -----------------------------
      - name: Deploy Prometheus & Grafana
        if: ${{ github.event.inputs.component == 'monitoring' }}
        run: |
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

          helm upgrade --install monitoring \
            prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            -f monitoring/prometheus-values.yaml

